interactions:
- request:
    body: ''
    headers:
      X-API-KEY:
      - REDACTED
      accept:
      - '*/*'
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      host:
      - beta-api.uspto.gov
      user-agent:
      - Mozilla/5.0 Python Patent Clientbot/5.0.16 (parkerhancock@users.noreply.github.com)
    method: GET
    uri: https://beta-api.uspto.gov/api/v1/patent/applications/16123456/meta-data
  response:
    content: '{"count":1,"patentFileWrapperDataBag":[{"applicationMetaData":{"firstInventorToFileIndicator":"Y","applicationStatusCode":150,"applicationTypeCode":"UTL","entityStatusData":{"smallEntityStatusIndicator":false,"businessEntityStatusCategory":"Regular
      Undiscounted"},"filingDate":"2018-09-06","class/subclass":"382/159","nationalStageIndicator":false,"firstInventorName":"Shoji
      KANADA","cpcClassificationBag":["G06N3/08","G16H30/20","G16H50/70","G16H30/40","G06N20/00","G06V10/7784","G06V10/774","G06F18/2178","G06N3/042","G06F18/217","G06F18/214","G06N3/045"],"effectiveFilingDate":"2018-09-06","publicationDateBag":["2019-03-28"],"publicationSequenceNumberBag":["0095759"],"earliestPublicationDate":"2019-03-28","applicationTypeLabelName":"Utility","applicationStatusDate":"2021-01-06","class":"382","applicationTypeCategory":"REGULAR","inventorBag":[{"firstName":"Shoji","lastName":"KANADA","inventorNameText":"Shoji
      KANADA","correspondenceAddressBag":[{"cityName":"Tokyo","countryCode":"JP","nameLineOneText":"Shoji  KANADA","countryName":"JAPAN","addressLineOneText":"c/o
      FUJIFILM Corporation","addressLineTwoText":"7-3, Akasaka 9-chome, Minato-ku","postalAddressCategory":"postal"},{"cityName":"Tokyo","countryCode":"JP","nameLineOneText":"KANADA,
      Shoji","countryName":"JAPAN","postalAddressCategory":"residence"}]}],"applicationStatusDescriptionText":"Patented
      Case","patentNumber":"10902286","grantDate":"2021-01-26","applicantBag":[{"applicantNameText":"FUJIFILM
      Corporation","correspondenceAddressBag":[{"cityName":"Tokyo","countryCode":"JP","nameLineOneText":"FUJIFILM
      Corporation","countryName":"JAPAN","postalAddressCategory":"postal"}]}],"firstApplicantName":"FUJIFILM
      Corporation","customerNumber":2292,"groupArtUnitNumber":"2641","earliestPublicationNumber":"US20190095759A1","inventionTitle":"LEARNING
      ASSISTANCE DEVICE, METHOD OF OPERATING LEARNING ASSISTANCE DEVICE, LEARNING
      ASSISTANCE PROGRAM, LEARNING ASSISTANCE SYSTEM, AND TERMINAL DEVICE","applicationConfirmationNumber":7051,"examinerNameText":"SABOURI,
      MAZDA","subclass":"159","publicationCategoryBag":["Granted/Issued","Pre-Grant
      Publications - PGPub"],"docketNumber":"1982-1042PUS1"},"applicationNumberText":"16123456"}],"requestIdentifier":"0904b301-2643-4647-9e82-eaa0eb5fdc36"}'
    headers:
      access-control-allow-headers:
      - Origin, X-Requested-With, Content-Type, Accept
      access-control-allow-methods:
      - OPTIONS,POST,GET
      access-control-allow-origin:
      - '*'
      content-length:
      - '2256'
      content-type:
      - application/json
      date:
      - Tue, 24 Sep 2024 18:17:18 GMT
      x-amz-apigw-id:
      - en1HUESgIAMFybg=
      x-amzn-requestid:
      - 0904b301-2643-4647-9e82-eaa0eb5fdc36
      x-amzn-trace-id:
      - Root=1-66f3022e-09c41d2b37a31c4c5f5c924f;Parent=5f6bcb3b83f64e46;Sampled=0;Lineage=1:33e8fdb8:0
    http_version: HTTP/2
    status_code: 200
version: 1
